require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OptionGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # OptionGroup. As you add validations to OptionGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all option_groups as @option_groups" do
      option_group = OptionGroup.create! valid_attributes
      get :index
      assigns(:option_groups).should eq([option_group])
    end
  end

  describe "GET show" do
    it "assigns the requested option_group as @option_group" do
      option_group = OptionGroup.create! valid_attributes
      get :show, :id => option_group.id
      assigns(:option_group).should eq(option_group)
    end
  end

  describe "GET new" do
    it "assigns a new option_group as @option_group" do
      get :new
      assigns(:option_group).should be_a_new(OptionGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested option_group as @option_group" do
      option_group = OptionGroup.create! valid_attributes
      get :edit, :id => option_group.id
      assigns(:option_group).should eq(option_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OptionGroup" do
        expect {
          post :create, :option_group => valid_attributes
        }.to change(OptionGroup, :count).by(1)
      end

      it "assigns a newly created option_group as @option_group" do
        post :create, :option_group => valid_attributes
        assigns(:option_group).should be_a(OptionGroup)
        assigns(:option_group).should be_persisted
      end

      it "redirects to the created option_group" do
        post :create, :option_group => valid_attributes
        response.should redirect_to(OptionGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved option_group as @option_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        OptionGroup.any_instance.stub(:save).and_return(false)
        post :create, :option_group => {}
        assigns(:option_group).should be_a_new(OptionGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OptionGroup.any_instance.stub(:save).and_return(false)
        post :create, :option_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested option_group" do
        option_group = OptionGroup.create! valid_attributes
        # Assuming there are no other option_groups in the database, this
        # specifies that the OptionGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OptionGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => option_group.id, :option_group => {'these' => 'params'}
      end

      it "assigns the requested option_group as @option_group" do
        option_group = OptionGroup.create! valid_attributes
        put :update, :id => option_group.id, :option_group => valid_attributes
        assigns(:option_group).should eq(option_group)
      end

      it "redirects to the option_group" do
        option_group = OptionGroup.create! valid_attributes
        put :update, :id => option_group.id, :option_group => valid_attributes
        response.should redirect_to(option_group)
      end
    end

    describe "with invalid params" do
      it "assigns the option_group as @option_group" do
        option_group = OptionGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OptionGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => option_group.id, :option_group => {}
        assigns(:option_group).should eq(option_group)
      end

      it "re-renders the 'edit' template" do
        option_group = OptionGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OptionGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => option_group.id, :option_group => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested option_group" do
      option_group = OptionGroup.create! valid_attributes
      expect {
        delete :destroy, :id => option_group.id
      }.to change(OptionGroup, :count).by(-1)
    end

    it "redirects to the option_groups list" do
      option_group = OptionGroup.create! valid_attributes
      delete :destroy, :id => option_group.id
      response.should redirect_to(option_groups_url)
    end
  end

end
